### ISSUE TITLE
University

### ISSUE THREAD

**Issue by Stelmashenko-A** [IstiN/schedule#6]
Wrong charset only in university, LecturerList hasn't this problem.
![screenshot 93](https://cloud.githubusercontent.com/assets/11212418/10450594/f9bf6f8a-71a3-11e5-926b-3fbfbca02975.png)

**Comment by IstiN** [comment]
Please google this problem and find solution ;)

Best Regards,
Vova

_Vladimir Klyshevich_

Grodno, Belarus (GMT+2)
Mobile phone:      +375 (29) 289-4325
E-mail:                  istin2007@gmail.com

Skype:                   uladzimir.klyshevich

2015-10-13 12:16 GMT+03:00 Стельмашенко Андрей notifications@github.com:

**Comment by Stelmashenko-A** [comment]
Hosted version works without any problems, all charsets are correct.
